<?php
class Admin extends CI_Model{

    public function getdata()
    {
        $select = $this->db->get('submissions')->result();
        return $select;
        //return parent::__get($key); // TODO: Change the autogenerated stub
    }
    public function kisi_yazdir($kisi_id){

        $select = $this->db->where("id",$kisi_id)->get("member")->result();
        return ($select);

    }
    public function kisi_bilgileri_yazdir($membername){
        $select = $this->db->where("membername",$membername)->get("member")->result();
        return $select;
    }
    public function getmembers(){
        $members = $this->db->get('member')->result();
        return $members;


    }
    public function Insertsubmissions($title,$content,$senddate,$membername,$about,$img){
        $submissions = "insert into submissions() values('','$title','$content','$senddate','$membername','$about','$img')";
        $this->db->query($submissions);


    }
    public function getmessages(){

         $messages = $this->db->get("messages")->result();
         return $messages;
    }
    function Insert($title,$content,$reciver){

        $data = array(
            'title'	=> $title,
            'content'	=> $content,
            'sender'	=> 'mustafa',
            'reciver'	=> $reciver,
            'date' => getdate(),

        );

        $query = $this->db->insert('messagebox',$data);


        /*
        SQL = INSERT INTO tablo (alanBir, alanIki) VALUES ('Ben alanBire eklenecek veriyim.', 'Ben alanIkiye eklenecek veriyim.')

        */

    }
    public function login($membername, $password){
        $query = $this->db->get_where('users', array('membername'=>$membername, 'password'=>$password));
        return $query->row_array();
    }
    public function form_insert($data){
        $this->db->insert('messagebox', $data);
    }
    public function saverecords ($title,$subject,$sender,$rec,$date)
    {

        $query="insert into messages() values('','$title','$subject','$sender','$rec','$date')";
        $this->db->query($query);
    }
    public function deleteposts($id){//Burada kullanici idyi de alarak sadece kendi postlarını silmesini sağla
        foreach ($id as $linenumber){
            $this->db->where('id', $linenumber);
            $this->db->delete('submissions');
            }

        }

}
